### ISSUE TITLE
Preview on Website does not work anymore - loading fonts fails because of CORS-error

### ISSUE THREAD

**Issue by elbosso** [google/material-design-icons#1091]
Website: https://material.io/resources/icons/?style=baseline

Error (Firefox) plenty more where that came from: 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/materialicons/v55/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2. (Reason: CORS request did not succeed).

Tested with: 
* Firefox 81 private and normal mode Ubuntu 18.04
* Version 85.0.4183.121 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by RoelN** [comment]
This seems to be fixed. Please reopen if you still have the issue!

**Comment by dastanaron** [comment]
The problem remained in the electron applications.

**Comment by omarshamali** [comment]
> This seems to be fixed. Please reopen if you still have the issue!

no its not i still get the error

**Comment by tphinney** [comment]
@omarshamali can you be more specific? Are you getting that error on Chrome on Linux like the original poster?

AFAICT this is not a problem with the font, nor directly with the serving of the font, per se.
Read for example this: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

“In many cases, it is caused by a browser plugin (e.g. an ad blocker or privacy protector) blocking the request.
Other possible causes include: …”

If this was a problem everybody hit, I think we would be seeing a LOT more concern than two inquiries a year and a half later… and in at least one case with a different source (Electron app on Chrome on Linux, instead of Firefox on Ubuntu Linux).
