### ISSUE TITLE
SVG sprites sheet documentation dead link

### ISSUE THREAD

**Issue by th0rgall** [google/material-design-icons#1126]
The documentation refers to a dead link regarding SVG sprite sheets: https://github.com/google/material-design-icons/blob/728a1ca7b0c0b73b3b42ce736bbc224839e04312/index.html#L369

This might be related to sprites missing overall, for example issue #349 (though the link mentioned there is also dead).

**Comment by RoelN** [comment]
Thanks for the issue! Sprites are no longer a part of the repo, as of version 4.0.0, but we're keeping track of whether they should come back or not here: https://github.com/google/material-design-icons/issues/1129

Mind if I close this issue in favor of that one? Feel free to re-open if you think otherwise.
