### ISSUE TITLE
Can't size accurately b/c extra space around the icon's viewbox

### ISSUE THREAD

**Issue by maya** [google/material-design-icons#1128]
How can I size the icons accurately with the extra viewport space all around the svgs?

<img width="72" alt="Screen Shot 2021-01-15 at 7 52 15 PM" src="https://user-images.githubusercontent.com/5249443/104796459-4410c900-576b-11eb-85de-0ed7acf5c5d3.png">

On your site, you're declaring them as 48px but the icon is smaller, only 40px when you subtract the extra viewport space that gets added.

**Comment by RoelN** [comment]
The 48px size is the size they're intended to be used at, not necessarily the size of the design of the graphic itself. All icons have a whitespace "buffer" to prevent them from running into the next icon or text. If you want to icon graphic to be 48px I suggest increasing the size to roughly 120%.

**Comment by maya** [comment]
@RoelN thanks for this response. Some other designers hypothesized that this was to allow for room for optical regularization. Can you confirm that this is not what it's for but for a buffer between icons? 

Thanks for the 120% tip. Will also have to consider techniques for alignment if using this (e.g. clipping, negative margins, etc.).

**Comment by RoelN** [comment]
@maya I'm not familiar enough with the reasoning of specific parts of icons, so I can't really comment on the optical regularisation stuff. But the fact that there some "breathing room" between icons so they don't touch is intentional.

By the way, another alternative would be to take the original artwork, clip it to your liking, and use that. Either way, good luck!

**Comment by RichMatthews** [comment]
@RoelN why would they provide breathing room? Surely that is the responsibility of whoever is consuming them? Adding breathing room means it's impossible to accurately provide consistent padding

**Comment by tphinney** [comment]
@RoelN is exactly correct.

The alignment is _part of the design_. Although the alignment for, say, a circle might seem obvious, throw in a triangle and some irregular shapes, and the alignment becomes non-obvious. ALL the icons fit within that design space (at least, at regular weight setting and smaller), and are visually aligned.

This is especially needed as there are MANY cases where there is a base design, and then some kind of modifier. There are many icons where there is a base icon and an “off” version with a slash through it (actually even more complicated, there is a virtual shadow where stuff is left out, this is not a simple mechanical operation). The alignment of these icons is done so that wherever humanly possible, the main part of the icon does not shift in the “off” version, so you can have a toggle that does not appear to “move” the main part of the icon. That wouldn’t be possible without having a definition of the area the icon lives in. We don’t want users to need to manually adjust them all.
