### ISSUE TITLE
Is there a way to get the newest icons

### ISSUE THREAD

**Issue by Gringoniceguy** [google/material-design-icons#1155]
Hello this repo seems to horribly out of date and not updated.
Is there a way to get the newest icon in a truetype format?
As the google official updated one at https://fonts.googleapis.com/css2?family=Material+Icons only seems to have woff2, and i wish to use this for desktop development so truetype only.

**Comment by tphinney** [comment]
The fonts are all getting updated more regularly now!
However, only the “regular” font is currently in TrueType... the others are OpenType CFF (OTF)—is that a problem for you?

**Comment by tphinney** [comment]
See also #1163

**Comment by tphinney** [comment]
FYI, OpenType CFF (.otf) is pretty well supported on the desktop. Native on Windows since Windows XP, and on Mac since OS X 10.0.

TTF is certainly more common, though, and there may be some environment that still rejects OTF. Please let me know if there is some particular app or situation you need that does not support OTF.

**Comment by tphinney** [comment]
Given no reply all week, and that the OTF vs TTF is captured in #1163, I am going to close this issue.
