### ISSUE TITLE
No difference between people and group icon

### ISSUE THREAD

**Issue by Whisper40** [google/material-design-icons#1181]
https://fonts.google.com/icons?icon.query=group
![image](https://user-images.githubusercontent.com/30440458/119266003-4a1b2880-bbe9-11eb-9129-03bd8d008df1.png)

**Comment by tphinney** [comment]
That’s not even the only identical icon!
BUT Google actually tracks these and has since deleted many of the duplicates in a major “cull” operation last year.

In the font version of the icons, the “old” names are still supported as a ligature, as well as the current icon name, even though the two point at the same single icon. This is the case for “people” in particular. “Group” is still there but “people” is not... but the name still works.
