### ISSUE TITLE
Bug with icons name

### ISSUE THREAD

**Issue by koala819** [google/material-design-icons#1190]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

[Here](https://next.material-ui.com/components/material-icons/) you have all your icons. 

## Expected Behavior 🤔

For example If I would like have the phone Icon, I see the name is Phone. 

But if I write this word I watch the Uppercase P and no the icon

## Steps to Reproduce 🕹

[Here](https://codesandbox.io/s/vibrant-violet-1sxwo?file=/src/App.js) a link to watch 2 icons : phone & phoneAndroid

## Context 🔦

I find how to display phone and androidPhone icons. But Twitter and Linkedin don't work.

I would like also use outlined icons, but I can with star_outlined, but not with Brightness2Outlined

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
   
```
  System:
    OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    Memory: 2.04 GB / 19.43 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  Managers:
    pip3: 20.0.2 - /usr/bin/pip3
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.3.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
  Virtualization:
    Docker: 20.10.7 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.56.2 - /usr/bin/code
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Perl: 5.30.0 - /usr/bin/perl
    Python3: 3.8.5 - /usr/bin/python3
  Browsers:
    Chromium: 91.0.4472.114
    Firefox: 89.0.2
  Monorepos:
    Yarn Workspaces: 1.22.5
    Lerna: 4.0.0
```
</details>

**Comment by tphinney** [comment]
The link is to a third-party site, not run by Google.
On Google's own site, searches are case-insensitive: "phone" "Phone" and "PhOnE" all return the same results, which include the desired icon. (e.g. https://fonts.google.com/icons?icon.query=PhOnE)

Now it is true that Google displays the icon names on their site with initial caps. But they also provide guidance for inserting the icon with the correct naming, using underscores instead of spaces, and all lowercase:

<img width="580" alt="Screen Shot 2022-05-03 at 11 40 07 AM" src="https://user-images.githubusercontent.com/6548266/166520906-8c67c19d-1e66-4e12-858d-644059173252.png">
s

**Comment by tphinney** [comment]
Do you think the display in the table at the left should ALSO display the names less friendly but more accurate, with all lowercase, and underscores in place of spaces? Or is the accurate code at right sufficient?

**Comment by tphinney** [comment]
I believe I addressed the issue. No feedback in months, so closing.
