### ISSUE TITLE
Meterial Design

### ISSUE THREAD

**Issue by Supersumepro** [google/material-design-icons#1241]
https://github.com/materialos/icons

**Comment by tphinney** [comment]
Hi! Not sure what the request is, but guessing it is to incorporate all those color icons at the repo link given?

Some of these are reproductions of Google’s own product icons. Google does not generally put Google product icons in the Material Symbols for third-party use.

All or most of the others seem to be third-party products, the icons for which are generally trademarks of those third parties. Google does not include those kinds of icons in their icon sets, either.

Also, these are nearly all full-color icons, and Google’s icons are not full color, as yet. (Although I am not sure if there is much of anything left if you drop icons due to the first two constraints.)

Let me know if there are any others I am missing?
