### ISSUE TITLE
Sign language icon

### ISSUE THREAD

**Issue by signly-projects** [google/material-design-icons#1243]
I'm really impressed by the amount of icons you guys have created. 

However, there's a missing one that represents sign language:

mdi-sign-language

Something like this would be brilliant:

https://fontawesome.com/v5.15/icons/sign-language?style=solid

**Comment by tphinney** [comment]
That was a great suggestion, and it has since been added! The icon name is "sign_language" and it looks like this in the default version:

<img width="211" alt="Screen Shot 2022-04-23 at 9 23 44 PM" src="https://user-images.githubusercontent.com/6548266/164956555-71ebcd45-7087-4653-9dc2-fe355d8eaf93.png">

It’s in the latest icon fonts, etc. Hope that helps!
