### ISSUE TITLE
Missing icon in symbols and other things

### ISSUE THREAD

**Issue by Ehmydev** [google/material-design-icons#1358]
Hello,

In Material Symbols, the icon 'source' doesn't exist anymore. It was the same as the icon 'topic' which exists, but while removing the duplicates don't you have kept the anteriority ?

Also in material symbols, icon 'file_upload' and 'upload' are the same, as well as 'file_download' and 'download'; and 'upload_file' doesn't have its counterpart 'download_file' as well as 'downloading' that doesn't have 'uploading'.

Anyway, thanks for the amazing icons here !

**Comment by tphinney** [comment]
Ah, that seems to be an error with “source.” I have fixed it for our next build.

The way this works is, with a very few exceptions, we don’t have duplicate glyphs in the actual font for Material Symbols. Instead we remove the duplicates, and then have extra code so that the single glyph has multiple codepoints, and we create extra  ligature code to preserve the ligature for the old name (even though the original corresponding glyph is gone). So I have done those extra steps to support the old “source” name.

When the standalone SVG icons are generated from the font, they base the icons generation on the list of ligature codes, so a single glyph can get re-inflated to be several (identical) SVG files.

I will file an internal issue to decide if we should also add “uploading,” but that isn’t a bug in the same sense.

**Comment by tphinney** [comment]
Note: Added the ligation code so you can type “source” and it invokes “topic”, which now has the additional codepoint U+F1C4 (as well as its old U+F1C8).
