### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by carla-1234** [google/material-design-icons#1372]
The Icon create is like edit icon .they don't have any difference
Both of them are pencil

**Comment by tphinney** [comment]
There are many such duplications in the Material icon sets (both the old Icons and the new Symbols); in Symbols I can say that they are deliberate, and some minor/accidental differences like just slightly different positioning or sizing of otherwise identical icons have been removed in Symbols.

In the Material Symbols font, there is only one glyph, “edit”; it has two codepoints, and the ligatures for “edit” and “create” points at “edit”; this allows us to support both of the old names and codepoints with just one glyph.
