### ISSUE TITLE
Missing icon 'auto_fix_high' in Symbols

### ISSUE THREAD

**Issue by Ehmydev** [google/material-design-icons#1380]
Hello again,

Like the title says, the icon 'auto_fix_high' is missing in Material Symbols while it exists in Material Icons.
I searched for the same icon with another name in Symbols, but couldn't find any.

Could you tell me if this is a bug or if it is intended ?

Many thanks

**Comment by tphinney** [comment]
Hmmm. So, in Material Symbols source we have "auto_fix" (identical icon, with the three stars) and "auto_fix_normal" (just one star), but neither makes it into Material Symbols because they are marked as Google-only.

Seems to me that is an error. We will need to add the rounded and sharp variants as well. Not sure what to do about the names, that is… troublesome.

**Comment by tphinney** [comment]
It may take some more time to percolate back into the real world, but this fix should be in an internal build tomorrow. (I did the first steps and passed it to a colleague to make the rounded and sharp variants.)

Thanks, @Ehmydev for the report!

**Comment by tphinney** [comment]
This was fixed and is publicly available now.
