### ISSUE TITLE
Warning design icon is still filled in outlined style

### ISSUE THREAD

**Issue by MaikKlassen** [google/material-design-icons#1388]
Hello,

I just used the release 4.0.0 for adding some icons in my project and was wondering that the warning icon (mdi_warning) like mentioned in the title looks the same filled and outlined.
It always look like this:
![image](https://user-images.githubusercontent.com/68427610/190602143-239a7b81-a035-446e-bc70-e8abcdea1308.png)
But should look like this outlined:
![image](https://user-images.githubusercontent.com/68427610/190602817-1a8fe74f-4b89-423f-a66e-7ece579b7bc3.png)

Could you tell me if this is a bug?

Thanks in advance

**Comment by tphinney** [comment]
We should have a newer formal release some time, as that was at least two years ago.

However, looking at the newest version of Material Icons, I see that there are two other versions of this icon under different names, so three versions altogether:
- "report_problem" has filled and outlined versions
- "warning" is always filled
- "warning_amber" is always outlined

I think this is clearly deliberate, so not exactly a bug. If you want the expected behavior, use “report_problem”

This is a good example of the kind of thing that we consolidated in doing Material Symbols. There is just one glyph in the variable font, and it changes states for outlined vs filled, and it is called “warning”
