### ISSUE TITLE
Remove duplicate icons with different names

### ISSUE THREAD

**Issue by chris-netizen** [google/material-design-icons#1394]
I found that there were two icons with different names, but the same design. 
The icons are;  notifications_on_outlined and notifications_active_outlined.

**Comment by tphinney** [comment]
There are many more identical icons in SVG format, not just that case!

In the newer version of the fonts, but especially Material Symbols, the duplicates are almost all weeded out. However, the old duplicate names and codepoints are still supported, pointing at the remaining glyph. But in the case of SVG files, it is more all-or-nothing.

Although they are not happy to have duplicates, once an icon is supported, Google doesn’t delete duplicates entirely because that could break people’s websites. So we don’t see these duplicates going away!
