### ISSUE TITLE
Fast going ti site for material symbols and icons

### ISSUE THREAD

**Issue by Carla-12345** [google/material-design-icons#1403]
I thought about this 🤔 
If someone need the icons ,must they go to site,download, and all the time will be lost.a key board will make the bug ok 👍 
Orange=material icons
Green=material symbols
Just essential, not all

**Comment by Carla-12345** [comment]
![Uploading Polish_20221021_105154030.jpg…]()

**Comment by Carla-12345** [comment]
<a href="https://uupload.ir/" target="_blank"><img src="https://s6.uupload.ir/files/polish_20221021_105154030_ksyy.jpg" border="0" alt="upload" /></a>

**Comment by Carla-12345** [comment]
Why don't u answer after 1 day?

**Comment by tphinney** [comment]
Sometimes replies will take more than 24 hours. My own objective is to _usually_ reply within a day or two. But that won’t always be practical. In this case, I read the request about 12 hours ago, but I wanted to think about it some more before I replied. Given that supplying such a thing would take months,  

A keyboard has to be downloaded and installed just as much as the font, and in fact is an additional thing to install besides the font. (Or one is building an app and needs installers.) So, providing a keyboard does not solve the problem of needing to download something.

Of course, things can potentially be pre-installed with Chromium or Android, that much at least is under Google’s control.

I think a bigger challenge with this suggestion is that there are over 2000 icons: picking 5% or fewer of those to be on a particular keyboard is tricky, and many or most users will have at least _some_ icons they need or want, which are not on the keyboard.

Personally, I think I would find it easier to remember an icon name and type that name to get the ligature with the font, rather than work with a custom keyboard.

But perhaps we are diving too far into details. I want to ask you a broader question: what is your use case for the keyboard? What is it you want to use it for adding icons to? General communications like messaging and social media posts? Or for app developers? Website developers?

**Comment by Carla-12345** [comment]
For the web developers
But..what we can do about this?
That everyone be able to use icons in site?
A font?

**Comment by tphinney** [comment]
Well, the icons have been supplied as fonts for quite some years now. That does not solve all possible issues here, though!

The Material Symbols do not have standard codepoints in Unicode. The font can be used to display the symbols via either private use Unicode codepoints, or ligatures based on icon glyph names (e.g. type "arrow_back" to get the icon).

But with over 2000 of them, using the existing https://fonts.google.com/icons site seems like a great way to browse them. Having multiple keywords per icon, and then searching on keywords is helpful.

**Comment by Carla-12345** [comment]
https://fonts.google.com/icons is good but i have a suggestion, the search bar has two 
icons beside.microphone(voice search) and camera(google lens)
I suggest you make another icon beside the mic and camera .for fonts.google.com/icons

**Comment by Carla-12345** [comment]
I,m bored,,,please answer

**Comment by tphinney** [comment]
When you say “the search bar” what are you even referring to?
What browser and OS are you on? Mobile or desktop?

**Comment by Carla-12345** [comment]
Hmm...it's hard to say about this
But i will make a simple picture
