### ISSUE TITLE
Conflicting icons for "Sim Card Alert" and "Sd Card Alert"

### ISSUE THREAD

**Issue by anantaraha** [google/material-design-icons#1408]
**Description:**
"Sim Card Alert" and "Sd Card Alert" literally have the same icons and cannot be distinguished from one another (Attached image). Because "Sim" and "Sd" are two distinct things, the icons should be different.

**Issue:**
![preview](https://user-images.githubusercontent.com/63910661/197622040-dfafdce7-43dd-4b33-841e-0c2532328835.png)

**Suggestion:**
All the Sim icons and Sd icons have similar shape. But in real life, Sd cards are slightly different. Modifying the Sd card's shape for all "Sd" card icons might help. In this way, if any "No Sd Card" icon is added in future, it will not conflict with "No Sim Card".

**Comment by tphinney** [comment]
> Because "Sim" and "Sd" are two distinct things, the icons should be different.

Is there a problem that, in context, people will confuse the two because the icon is not distinct? Will somebody misinterpret a SIM card alert as being an SD card alert? 

I would have thought not, as I expect one would only get either of these alerts (or card-missing notifications) right after doing something with the relevant card, and one would be very aware of which card one was messing with.

Would making the icon subtly different (e.g. by mirroring one set of the icons to point the other way) help; is there much chance the average user would know which is which? 

I ask because making the icons look slightly different from each other does not mean one has accomplished actual communication (IMO).

In the font version of Material Symbols, we actually save space by having only one glyph for both: there are two ligatures and two codepoints, but all point at the one glyph.

**Comment by tphinney** [comment]
If we _were_ going to make a change, I would suggest we horizontally mirror the design for both the SD card related icons: sd_card and sd_card_alert

Of course sd_card is already distinct, but the alert icons are the same, and we want to carry over whatever design change we make for that one, so…

**Comment by anantaraha** [comment]
Yes, only the alert icons are similar. If any changes are to be made, and all SD card related shapes get chnaged, I think [https://en.wikipedia.org/wiki/SD_card](https://en.wikipedia.org/wiki/SD_card) the microSD like corner cut should look better.
