### ISSUE TITLE
Options for the Old Icons are missing after the latest UI Rework

### ISSUE THREAD

**Issue by SvenBudak** [google/material-design-icons#1575]
Options for the Old Icons are missing after the latest UI Rework of: https://fonts.google.com/icons?icon.query=comment&icon.style=Rounded&icon.set=Material+Icons&icon.platform=web

its not possible anymore to get for example the add comment icon, without filled out and rounded.
Also it is not possible anymore to change the line widht of the old icons. so it is impossible for us, to add new icons to our app which uses the old icons in 200 line width...

**Comment by tphinney** [comment]
On the first item, it sure looks to me like you are mistaken. I just change the dropdown to the “outline” set and there it is. (On the left, fourth icon down.)

<img width="519" alt="Screenshot 2023-09-26 at 7 49 48 PM" src="https://github.com/google/material-design-icons/assets/6548266/bb541518-a446-4501-9768-958a0e2ecced">

If you have a second distinct issue, please file a separate issue for it instead of throwing it in as an extra thing in this issue.

On the second point, it was NEVER possible to change the line width (a.k.a. weight, stroke weight) of the old icons. That is a capability that was added with Material Symbols, and never retrofitted back to the old Material Icons. I know this pretty well, as I designed the weight variation scheme myself and implemented it in the variable font. There was never a variable-font source for the old Material Icons.
