### ISSUE TITLE
Icon Request: output

### ISSUE THREAD

**Issue by joaobarcia** [google/material-design-icons#160]
Hi, thanks for the great lib.

There is an "input" icon but no "output" icon. This would be extremely valuable for us.

Cheers

**Comment by mahmuodmasri** [comment]
+1

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons

**Comment by kevincox** [comment]
Hi, I was interested in using the input and output icons however they are different shapes. The input icon is noticeably shorter and wider than the output. This means that if you line them up next to each other they look quite funny. Is this intentional or should the have the same size and aspect ratio?

Open in different tabs and switch between to compare:

- https://fonts.gstatic.com/s/i/materialiconsoutlined/output/v1/24px.svg
- https://fonts.gstatic.com/s/i/materialiconsoutlined/input/v1/24px.svg

Image of them side-by-side:

![image](https://user-images.githubusercontent.com/494012/153289109-9bd739cc-a625-49d4-ac56-a2a735279ce7.png)

**Comment by kevincox** [comment]
I made a fixed version which uses the shape of the output icon. I simply flipped the box and then aligned the arrow to the left side. 

I don't know how the sources of this project are created but here is the fixed version. I release it under Apache 2.0 for anyone who wishes to use it.

```svg
<svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><polygon points="12.17 13 9.59 15.59 11 17 16 12 11 7 9.59 8.41 12.17 11 3 11 3 13"/><path d="m5 19h14v-14h-14v2h-2v-2c0-1.1 0.89-2 2-2h14c1.1 0 2 0.9 2 2v14c0 1.1-0.9 2-2 2h-14c-1.11 0-2-0.9-2-2v-2h2z"/></svg>
```
