### ISSUE TITLE
Icon Request: Button

### ISSUE THREAD

**Issue by Doge-is-Dope** [google/material-design-icons#1640]
I couldn't find an icon for "Button". Is there any alternative or suggestion? Thanks

**Comment by tphinney** [comment]
doing a search on “button” worked for me

https://fonts.google.com/icons?icon.query=radio+button
or for a wider range of things
https://fonts.google.com/icons?icon.query=button

**Comment by Doge-is-Dope** [comment]
Hi, thanks for the reply! When you search "button", you'll get 18 icons. However, just like some of these icons, switch, checkbox and radio buttons, what I need is an icon that represents the component "Button" itself. 
For your reference, check out [Material Design - Button](https://m3.material.io/components/buttons/overview).

**Comment by tphinney** [comment]
Ah, you don’t just mean a button. You mean a button _that you can put text on_.
But these would need to be of highly variable width, because the width of the text varies. Maybe variable height as well?
I suspect this is impractical. But if it were to be done, it would be a substantial group of icons, not just one. Super problematic also because the font is monospaced, and all icons in the font have to work within the same “advance width” (horizontal space allocated to them).

I think you probably need to do this in some other environment. Font glyphs in the existing Material Symbols are not a very good vehicle for a general solution to this problem. IF it were done as a font, it would likely as a separate font with variable font axes for width and maybe height.

**Comment by tphinney** [comment]
As discussed, the massively variable width needed for this is a non-starter in a monospaced set of icons, so I am going to go ahead and close this for now.  🙁
