### ISSUE TITLE
Error in sharp/edit_square symbol

### ISSUE THREAD

**Issue by Eisenbert** [google/material-design-icons#1696]
There is a fine line in the symbol where it doesn't belong: 
![image](https://github.com/google/material-design-icons/assets/124776489/9e9cd89e-3358-4892-8fcd-11282eb55775)

**Comment by tphinney** [comment]
Oh, nice catch. Yes, this can be fixed.

**Comment by imrikim** [comment]
@tphinney any ideas when this exact icon will be accessible ?

**Comment by tphinney** [comment]
@imrikim The updated Material Symbols icon with fix included has been available for a month or more. This repo was updated with updated SVGs a month ago, AFTER the fix. The current live Material Symbols font that has been available for weeks from Google Fonts has it (and I think it was in previous versions, but have no quick way to check).

Whether Flutter is taking this fix is a downstream issue for the Flutter folks. Also, whether they have or you are requesting Material Symbols (the currently maintained icons) instead of Material Icons (several years old now) is something I would wonder about.

Equally importantly, what you show above: (1) does not show the bug this issue is about; and (2) is NOT the “sharp” version of the icon which had the bug (the code shown is requesting  the regular icon, and getting it, although a filled version of it, not sure if there is more code not shown that is causing that). 

So I am not clear what the complaint is, nor why it is tacked on to this unrelated issue. Please open a new issue if you are seeing a different bug (e.g. getting a filled version of the icon instead of an unfilled one?), other than the one this issue is about.
