### ISSUE TITLE
Some icons looks blurred at 300 weight, 20 opsz, 20dp.

### ISSUE THREAD

**Issue by felipefarinon** [google/material-design-icons#1728]
The 'description', 'book 4', 'folder', 'add circle' and 'add' icons look really blurred at 300 weight, -25 GRAD and 0 GRAD, 20 opsz. Their lines fall almost exclusively at half pixels [1]. Funnily enough, the 'description' icon with the same params but 24 opsz resized to 20dp is sharper than the one with 20opsz [2]. Since 20opsz is a recommended size, I'd expect the icons to look crisp.

Are weights and grades generated automatically? Can we hint the shapes so that they fall closer to the pixel boundaries?

20opsz at 20dp / 24opsz at 20dp
![image](https://github.com/google/material-design-icons/assets/17036813/36e8829b-5057-4af0-9724-64fc1e4cfe52)

[1]
![image](https://github.com/google/material-design-icons/assets/17036813/2c4087fa-c07b-4713-83a2-a3f2e313d034)

[2]
![image](https://github.com/google/material-design-icons/assets/17036813/a4527db8-490f-45d6-9d16-00492509fcfc)

**Comment by tphinney** [comment]
Note first that the 20 px design-size outlines are designed to fall at a mix of full-pixel 
(for outer edges, usually) and half-pixel (for inner edges, usually) boundaries. The standard stroke thickness at 20 px size is 1.5 px (2 px at 24 px). On devices with either 2x or 4x pixel density these will still look very crisp. On devices with 3x pixel density, the outer edges will usually look crisp, but not so much the inner.

That said, yes, if you additionally adjust weight and grade off the defaults, the icon will no longer fall on pixel boundaries. If having the crispest possible rendering is important to you, you should stick to 20 and 24 px sizes, and not change the weight or grade settings.

The effects of hinting vary dramatically depending on the viewing device, but on most modern devices, you cannot _guarantee_ pixel-snap based on hinting. (Apple rendering ignores all hinting at _all_ useful sizes, and they are about half of the market in US/Canada, western Europe, Japan and Australia. Over a quarter of the market worldwide.)

**Comment by felipefarinon** [comment]
Thanks for the quick reply.

So the icons are designed to be crispest at 20 and 24px, with 400 weight and 0 grade, and any other variation with different weight/grade values are generated automatically? I'd expect that, even with the automatic generation, there could be predictable guarantees that some other weights or grades would fall close to full-pixel alignment. If those guarantees exist, what are they?

It'd be unfortunate if there's no crisper lighter weight, since it would make it more difficult to pair this icon set with fonts that are rendered thinner at weight 400, like the default Windows font, Segoe UI, when rendered using GDI (which applies subpixel AA) or DirectWrite. In the image below, the icon in the first line doesn't pair well with Segoe UI, the one in the second line pairs better (its outline is almost 1px aligned to a full pixel).

![image](https://github.com/google/material-design-icons/assets/17036813/23892648-ee00-429e-a0bc-7a5773b3845c)

That's useful information, I wish the design guidelines included more specific instruction about issues like this.

**Comment by tphinney** [comment]
“So the icons are designed to be crispest at 20 and 24px, with 400 weight and 0 grade,”

Yes. Although, there was quite a while when the 20 px was not set up with pixel-perfect alignment.

”and any other variation with different weight/grade values are generated automatically?”

Well, that depends on what you mean by “automatically”—I would say “no.” With a four-axis font like this, it is not as if there is only one or two master designs that are distorted, that is not how variable fonts work. You need master designs to create all the axes of the design space. In this case, besides the “Regular” (24 px design), there are handmade masters for various extremes of the font: the 100 (thin) and 700 (bold) weights of the Weight axis; the weak (-50) and strong (+200) grades of the Grade axis; the 20 px and 48 px sizes of the optical size axis, and the filled variant of the Fill axis. However, of all those, only the 20 px and 24 px masters (and their filled counterparts) are grid-snapped.

We have seven weights, the 100 weight is just over half a pixel, and the 700 weight is a tad more than three pixels. Nothing on the grade axis amounts to a full pixel added or subtracted. Because of interactions between rendering size and weights, even if we had made our weight axis have some specific pixel breakpoints, they would by default only work at one size.

The way variable fonts work is, all *other* combinations are created by vector addition, using the info from the designed masters. (Mind you, one _can_ have as many designed masters as one likes, up to 64K. So one _could_ put them in all the corners, at the cost of major increases in production work and file size.)

So, in the font as it stands, you ask for 22 px and you will get something interpolated halfway between the 24 px (default, regular) design and the 20 px design. Ask for 48 px bold, and it will be achieved by vector addition, which is to say moving the points (1) the amounts needed to get from the 24/Regular to the 48 px version, PLUS (2) the amounts needed to get from the 24/Regular to the Bold version.

That is the simple part. There is another layer of complexity I will encourage most readers to just ignore, but I will explain here for the sake of accuracy and completeness. I would not want to mislead you!

In some cases, combinations produce undesirable effects. For example, the masters for Thin (-100) weight, Weak (-50) grade and 48 px opsz all make strokes thinner—especially the Thin weight. So the combinations of those would be problematic. Similarly so at the bold end of the spectrum where some shapes could get clogged/closed. To deal with that, I invented “synthetic masters”: we take a design coordinate position from _inside_ the design space, and then “promote” that coordinate position to be an outside-corner master (by creating glyph outlines using those coordinates, and then defining that as an additional master). This effectively warps the design space so that certain “bad things” can be avoided. So for example, the synthetic Strong Bold master takes the interpolated style that has the Bold weight but only 76.67 Grade, and uses that at Bold weight and 200 Grade. Which makes it so that when you are bolder than Regular weight, the bolder you get, the less impact adding positive Grade has.

Within a few years I hope support for version 2 of the 'avar' table will be widespread, and we will achieve the identical effect by warping the design space directly without needing the synthetic masters _per se_. Our font file size will drop significantly! But the concept will be the same (and the effects, one hopes), just the under-the-hood part will be implemented differently.

Why yes, this is pretty complex, and the full set of synthetic masters (or avar v2 warpings) is substantial. The synthetic masters add 12 synthetic masters to the 14 designed ones, although half of those are just filled versions of base glyphs.

At this point, I expect you can see why this is not in the public docs at this time. That is a lot to take in, may not even be clear from this (would benefit from a bunch of graphics to explain!), and even then most people who are just normal users interested in the icons have long since lost any interest.  😬

**Comment by felipefarinon** [comment]
So I guess that I'll gravitate towards the thinner weights, to try to get the icons that approximate strokes of 1px, even though they don't snap to the pixels perfectly. Otherwise 2 or 1.5px strokes make the icons look too bold to match font I'm using.

In the longer term, it seems that what I need is different from what the material symbols provide, since what I really need is pixel perfect and thin (1px strokes) with sizes 18, 20 and 24px, so I might end up picking another icon set.

Thanks a lot for taking the time to explain this thoroughly. I'd love to read more about it in the future.
