### ISSUE TITLE
Index.html in release vs in repository

### ISSUE THREAD

**Issue by FizzyPopStudios** [google/material-design-icons#173]
When you download the zip file the index.html file contains a catalog of all icons in the collection, however, when I cloned the git repo the index.html file contains documentation on using the library.

There seems to be some sort of conflict, the zip file does not contain a file containing documentation, and I do not see a catalog like html file in the repo.

Perhaps keep the index.html file as the documentation file and change the catalog file to catalog.html so both the repo and the zip file contain both files?

**Comment by pconstrictor** [comment]
I'm here because I downloaded the ZIP and didn't see any easy way to browse the icons. It contained no HTM / HTML files at all. 

Workaround: search the root folder, including all subfolders, for files containing `black_24dp.png` . If I search for `setting black_24dp.png` (in Windows Explorer) I mostly get one thumbnail for each matching icon, and 'only' seven hits for ic_settings_system_daydream_black_24dp.png

The readme.md file didn't help me.

I then cloned the repo instead. It does have one HTML file (index.html) which is the same content as https://google.github.io/material-design-icons/ . It has a promising-sounding link, "Browsing and downloading individual icons; The complete set of material icons are available on the material icon library."
https://www.google.com/design/icons/ 

That works, and it's searchable if you can guess at least part of the filename.

Having a better search supporting tags/keywords would be nice, though the quick and dirty way to do that would be to have really long filenames.

**Comment by GirlInTheShell** [comment]
In my local version that I cloned I kept the index.html the same; the basic information about the collection, how to use it etc.

I then created a file titled "catalog.html", which then contains the thumbnails for all the icons in the collection.

I would suggest perhaps doing something similar so this issue can be resolved in the future. Having index.html contain info about the project and catalog.html contain the... well, catalog, is probably a nice and tidy solution! :)

**Comment by shyndman** [comment]
I'm closing this off. We don't have an index.html anymore.

Please use the [icon library](http://www.google.com/design/icons/) or look at sprite sheets in [/sprites](https://github.com/google/material-design-icons/tree/master/sprites/css).
