### ISSUE TITLE
Inconsistent IOS forward / backward arrows alignment

### ISSUE THREAD

**Issue by dezhin** [google/material-design-icons#1744]
Hi, the arrow_forward_ios icon is center aligned, but arrow_backward_ios is left aligned. Is it a bug or a feature?

![image](https://github.com/user-attachments/assets/344b67c9-0148-415b-b407-eab217712106)

**Comment by tphinney** [comment]
When originally implemented, the icon was misaligned. As people presumably compensated for that, rather than mess up existing implementations, a corrected version was added as “arrow_back—ios—new”

All long before my time, both were already in place several years ago.

**Comment by dezhin** [comment]
Got it, not breaking anything seems reasonable. I see `arrow_back_ios_new` in Material Icons (deprecated), but there is no such icon in Material Symbols (new) which is on the screenshot.

**Comment by tphinney** [comment]
Hmmm. The icon is present in the font. So that must mean its viewing is being suppressed in the front end viewing. Seems like a bug.

But it does mean that even if you can’t view it in the interface, you can call it by name or codepoint. Name was given, codepoint is E2EA

I will see about getting the front end fixed as well

**Comment by tphinney** [comment]
OK, got agreement to un-hide it on the front end as well.
When the front end gets updated is TBD, but it should come through on the next update.
