### ISSUE TITLE
social network, corporate and festive icons

### ISSUE THREAD

**Issue by GbrlSouza** [google/material-design-icons#1745]
Hi, how are you? Could you please add social network icons? If possible, also add corporate and festive icons! Thank you!

Gabriel Souza - Campinas, São Paulo, Brazil.

**Comment by tphinney** [comment]
Can you be more specific as to what specific corporate or festive icons you have in mind?

Social Network icons: Generally, Material Icons has a polocy of not adding icons for other company’s trademarked logos. Indeed, some of these were previously removed. So that would include icons for things like Facebook, X/Twitter, etc.

This would also apply to icons based on company logos, if that is what you mean by “corporate” icons.

**Comment by GbrlSouza** [comment]
Hi, what's up?

I understand the policy of not adding icons with registered logos. I'll try to be more specific:

Social media icons: These would be generic, without using trademarks. Something that represents, for example, “social connections” or “digital networks”.
Corporate icons: I was thinking of elements such as file folders, graphics, contracts or images representing teamwork.
Festive icons: These can be generic, such as balloons, confetti, presents or fireworks, disco balls, without direct references to specific brands or events.
I hope this helps! If you need any more details, just let me know.

Thanks! 😊

**Comment by tphinney** [comment]
Oh, that is more clear and somewhat helpful. But it seems like you haven’t really looked at what is already available. For example, a search on “folder” would show a variety of icons. If there is some specific word/concept/thing you need that is not covered, please say what it is.

Corporate icons: I would say we have all those already! If there is something specific you need that is missing, please specify. 

Festive icons: same! See /celebration /cake and /featured_seasonal_and_gifts (yes I know it is a goofy name, but the icon is a present)

social media icons: search on hub, share, team

**Comment by GbrlSouza** [comment]
Oh yes, I see.
Thanks for the reply, it helps.
