### ISSUE TITLE
Document usage of underscores in ligatures more clearly

### ISSUE THREAD

**Issue by shyndman** [google/material-design-icons#184]
It's confusing because it differs from the icon name

**Comment by miguelcobain** [comment]
Can we *please* get dashes instead of underscores? :cry:

**Comment by miguelcobain** [comment]
Can we **please** get dashes instead of underscores? :cry:

**Comment by worthlutz** [comment]
This is still an issue.  I struggled with the lack of documentation regarding the need for underscores on multi-word icons.

Google eventually led me to issue #177. Which led me here.

**Comment by jokerosky** [comment]
Also faced with the problem. For example, I've tried to use **menu_book** , but instead, it shows two icons: 'menu' and 'book'.  Same time **restore_page** works, and **restore_from_trash** not.

First, i thought that using codepoints could help https://github.com/google/material-design-icons/blob/master/iconfont/codepoints
but seems that the problem is an outdated repository and, the same time, new icons on the page: https://material.io/resources/icons/?style=baseline

**Comment by n4bb12** [comment]
Stumbled over `menu_book` as well.

**Comment by constagorgan** [comment]
I had the exact same problem.

**Here's what worked for me:**
You'll have to use the latest version of the font.

So either fetch the resource directly from Google / add this to your code:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**o͙r͙** go to: [fonts.googleapis.com/icon?family=Material+Icons](https://fonts.googleapis.com/icon?family=Material+Icons) and copy this URL:

![image](https://user-images.githubusercontent.com/9217700/102537339-7d461280-40b3-11eb-8407-4f32c1877335.png)
(I pasted the screenshot instead of the URL because the file contents / the source URL might change over time)

Hope it helps!

**Comment by Retroguru** [comment]
I can confirm, that this issue still exists. ```create_new_folder``` shows no icon, but spaces, and ```sync_saved_locally``` shows three icons instead a computer with checkmark in it.

I am trying to self-host the font. But it seems that I have to use the SVG instead.

**Comment by tphinney** [comment]
First, I hope recent commenters realize they are piling on an UNRELATED issue?

The issue is, we need to do a better job of documenting how ligatures work in icon names.
Actually, that has been done, so I am closing the issue.

Also, I will note that one weakness with the ligature usage, that perhaps should be documented, is that the ligature code will not work if the text breaks over a line ending. This is just because of how OpenType ligatures and line layout work, not at all apparent there is a reasonable fix for it.  :(

If you have an issue with a specific ligature NOT WORKING in any other way, then please specify very clearly whether it is Material Icons or Material Symbols, and create an issue for it.
