### ISSUE TITLE
replacing svg sprites with symbol maps

### ISSUE THREAD

**Issue by jpc-ae** [google/material-design-icons#223]
Symbol maps offer greater advantages than sprite sheets as they can be used without repeating the view-box dimensions or setting a y attribute. I created a pull request with an example of how a symbol map file is used. A sprite sheet could be added to the file for legacy purposes and viewing directly by adding use elements for each symbol at the end.

**Comment by shyndman** [comment]
Hey @jpc-ae,

Because I had a release planned, I decided to add support for this feature myself. You can find your symbol sprites sitting alongside the identifier based sprites in [sprites/svg-sprites](https://github.com/google/material-design-icons/tree/master/sprites/svg-sprite).

I've also added support for their generation in our Gulpfile so they'll stay up to date.
