### ISSUE TITLE
Icons request: remove link, superscript and subscript

### ISSUE THREAD

**Issue by GabiAxel** [google/material-design-icons#227]

**Comment by shyndman** [comment]
Had a bit of a parse failure on this title, but I got it. ;)

**Comment by adarshv90** [comment]
+1

**Comment by rebecamendez** [comment]
+1

**Comment by ravinderpayal** [comment]
+1

**Comment by flundermicha** [comment]
+1

**Comment by fdemian** [comment]
+1

**Comment by lakewood999** [comment]
+1

**Comment by chrismackie28** [comment]
+ 1 superscript and subscript

**Comment by Domino987** [comment]
+1

**Comment by kcak11** [comment]
Do we have any update on this issue ?

It will be great if the missing icons are included sooner. 
_Thanks in advance._

**Comment by jjsiman** [comment]
+1

**Comment by danitag78** [comment]
+1

**Comment by milelo** [comment]
+1

**Comment by margox** [comment]
still missing :(

**Comment by RoelN** [comment]
The `link_off` icon is here:

<img width="354" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108855935-cea9db00-75e9-11eb-8580-29bb3809a6f5.png">

As well as subscript and superscript:

<img width="343" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108856055-f13bf400-75e9-11eb-88ed-7a014573effd.png">

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
