### ISSUE TITLE
CPU heavy installation

### ISSUE THREAD

**Issue by findkiko** [google/material-design-icons#234]
A bower install pulled in this dependency. Is this package doing substantial post-install processing?
after seeing warnings from #74 my CPU maxed out for minutes on end. Although the installation finished eventually I was close to killing the process assuming a fault.

If this is a known pre-processing step. I'd advise adding some kind of NOTICE: output so an unfamiliar user understands that this install is meant to take several orders of magnitude longer than all the other packages being pulled in.

**Comment by shyndman** [comment]
Nope, no pre-processing.

**Comment by shyndman** [comment]
It does extract a zip file packed with thousands of small images, then the installation step copies those images into the local directory. I suspect that's what's responsible.

We may be splitting the repo into format-specific packages at some point, which will help the situation, but we're not there yet.

We're [tracking that issue here](https://github.com/google/material-design-icons/issues/14). I'll be closing this bug off.

**Comment by findkiko** [comment]
OK, thanks for the quick feedback. I have noticed that unzip is slow on this rig, so that explains what I saw.
