### ISSUE TITLE
Add Base64 option - Font icons doesn´t render on iOS devices with some content blockers

### ISSUE THREAD

**Issue by kallehansson** [google/material-design-icons#252]
When using an iOS 9 device with an activated content blocker set to blocking web fonts the icons will not render.

One way of adressing this could be to add the choice of using Base64 Encoding when embedding the font.

Attached screenshot of https://www.google.com/design/icons/ in Safari on iOS9 with a webfont blocking content blocker:

![google_design_icons_blocked_webfonts_151119](https://cloud.githubusercontent.com/assets/4726062/11442182/78634a40-9513-11e5-986e-61905b19b517.jpg)

**Comment by shyndman** [comment]
Are you asking for us to provide you with CSS that embeds the fonts?

I agree that it's probably unexpected from the user's standpoint for their content blocker to block icons, but frankly, if they're running a content blocker things aren't always going to work properly.

**Comment by jestelle** [comment]
I have a feeling this is something we can't fix.

If someone blocks web fonts, our web fonts wont work ;-)

Now the question remains as to whether there's a way to work around web-font-blockers.  Sounds like your suggesting embedding the font into HTML or CSS, instead of loading it as a separate resource?

We might be able to look into this, but it's unclear to me if it's a good idea.

I'm going to close this for now, but please reopen if there is any concrete ideas of what we could do here.
