### ISSUE TITLE
Icon request: Lifesaver

### ISSUE THREAD

**Issue by Sjennon** [google/material-design-icons#303]
I would love to find an icon representing a lifesaver. I coulnd't find it.

![image](http://www.ci.k12.mn.us/html/images/Life-Saver-icon.png)

**Comment by RoelN** [comment]
The link doesn't work, could you explain how a lifesaver icon would look?

Or will this one work?

<img width="172" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108852835-5beb3080-75e6-11eb-8502-6246d4f1e38d.png">

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
