### ISSUE TITLE
Request: Temperature Unit Icon

### ISSUE THREAD

**Issue by arzbhatia** [google/material-design-icons#339]
Maybe an icon for temperature unit? Switching from F to C & vice-versa.

**Comment by RoelN** [comment]
These icons are now part of the set:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/4570664/107760447-08e1c580-6d2a-11eb-9caf-15f342961b63.png">

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
