### ISSUE TITLE
Social Icons

### ISSUE THREAD

**Issue by akabhirav** [google/material-design-icons#350]
Icons such as facebook, twitter, google+, linkedin, whatsapp, etc are still not there

**Comment by abdonrd** [comment]
+1

**Comment by emanb29** [comment]
+1 I think social/brand icons are an absolute necessity for any icon font. That said, i think they'd be best suited to an extension rather than the core font set, as they could be pretty heavy for a somewhat unnecessary addition. Perhaps an icoMoon-like icon set builder would be a good solution, or more simply, just a separate font file.

**Comment by shyndman** [comment]
Closing this off. Read https://github.com/google/material-design-icons/issues/166#issuecomment-161462433 for more info.
