### ISSUE TITLE
Bathroom icons

### ISSUE THREAD

**Issue by nffdiogosilva** [google/material-design-icons#359]
Issue open to request bathroom icons

**Comment by R4mpancy** [comment]
Kind of surprised that this is missing from the list of icons. Especially considering there is one for a **hot tub?** I can see how it could be a somewhat biased icon based on somebody's region, but most bathrooms have at least a sink which could be a possible addition.

**Comment by RoelN** [comment]
@nffdiogosilva These icons are now available:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/4570664/107756258-404d7380-6d24-11eb-9c40-3b6a984e2fda.png">

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
