### ISSUE TITLE
Icon request: hashtag

### ISSUE THREAD

**Issue by The-Don-Himself** [google/material-design-icons#456]
First, wonderfully designed icon set I must admit.

I think it would be awesome to include a hashtag icon.

**Comment by valerio-bozzolan** [comment]
You can appreciate the character `#`  itself :sunglasses:

Think about it.

**Comment by The-Don-Himself** [comment]
@valerio-bozzolan 
Do you mean doing something like this?
````
<i class="material-icons">#</i>
````
I have a social commerce kind of [app](https://campus-discounts.com) where I add hashtags to category names to let you see products in a tweeter kind of way. This is how the hashtag icon looks
````
<i class="material-icons">#</i>Snacks, Cakes and Desserts
````
Result
![hashtag](https://cloud.githubusercontent.com/assets/5156320/18652323/1fc483e8-7eda-11e6-90b6-8dc5f6f46d1a.jpg)

Not nice at all. Maybe I am mistaken, what be your suggestion?

**Comment by valerio-bozzolan** [comment]
Oh sorry, you are right. Try with:

    <span class="m4gic-googl">#<span> Ice-creams

I hope that the code will compile also for you to get a perfectly in-line icon of an hashtag and then the word ice-cream.

**Comment by joelday** [comment]
It's ubiquitous as an icon and it makes sense to provide it as such so that 1. you can use a common icon hosting component instead of conditionally switching to a text based component, 2. not have to  manually style it, 3. not require the font if you're otherwise using SVGs and 4. have consistent rasterization of the icons in various browsers.

@valerio-bozzolan, I'm sorry, but I feel I have to make the observation that your response, albeit 😎, was pretty shortsighted and condescending. Not the kind of thing that makes people feel good when there's a comment on their GitHub issue.

**Comment by valerio-bozzolan** [comment]
I only wanted to say that a cute `#`, as a cute `A`, or a cute `s` and `d`, can be found in any normal web font. And we don't know why some web fonts provides characters and not icons, but this provides icons and no characters. That's a bug?

Not funny? OK. ¯\\_(ツ)_/¯

**Comment by The-Don-Himself** [comment]
I just brushed it off as a misunderstanding. It seems like @valerio-bozzolan is from Italy, I'm from Kenya so I reckon miscommunication can happen. That said, the only thing I wish @valerio-bozzolan could change is the confused reaction emoji he tagged this issue with.

For those still looking to get this, I found manually adding some styling achieves a near perfect result

````
<i style="vertical-align:text-bottom; font-weight:bold" class="material-icons">#</i>
````

Gives

![hashtag](https://cloud.githubusercontent.com/assets/5156320/23389505/5ff5d354-fd79-11e6-9921-fdfecb94efb2.png)

**Comment by retnikt** [comment]
Why not add it? A hash is more than punctuation. It can represent:
- a stylized bullet point in a list
- link anchors
- tags, as in social media or SEO
- checksum/digest/hash algorithms
- social media in general
- a grid
- tic tac toe

Icons8, for example, has 208 icons for a hashtag. https://icons8.com/icons/set/hash

This:
> ```
> <i style="vertical-align:text-bottom; font-weight:bold" class="material-icons">#</i>
> ```
is inadequate as a workaround, because many applications, frameworks, and libraries, allow you to input an icon name/ID from Material Design icons, but not just custom HTML to display a fake icon.

This icon could easily just be the bold italic hashtag from Roboto or something like that, converted, or if you want to design it from scratch, it would still take like 10 minutes, right?

**Comment by valerio-bozzolan** [comment]
> Why not add it? A hash is more than punctuation. It can represent:
> 
>     * a stylized bullet point in a list
> 
>     * link anchors
> 
>     * tags, as in social media or SEO
> 
>     * checksum/digest/hash algorithms
> 
>     * social media in general
> 
>     * a grid
> 
>     * tic tac toe
> 
> 
> Icons8, for example, has 208 icons for a hashtag. https://icons8.com/icons/set/hash
> 
> This:
> 
> > ```
> > <i style="vertical-align:text-bottom; font-weight:bold" class="material-icons">#</i>
> > ```
> 
> is inadequate as a workaround, because many applications, frameworks, and libraries, allow you to input an icon name/ID from Material Design icons, but not just custom HTML to display a fake icon.
> 
> This icon could easily just be the bold italic hashtag from Roboto or something like that, converted, or if you want to design it from scratch, it would still take like 10 minutes, right?

Just a punctuation. What you are talking about, "custom HTML", it's CSS. If you define a classname inside your CSS, from the user perspective it's just a matter of using it:

```
<i class="material-icons-font-custom-name-foo">#</i>
```

**Comment by hbugdoll** [comment]
Hashtag icon `tag` was added in v4.0.0:
https://github.com/google/material-design-icons/tree/4.0.0/src/content/tag

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
