### ISSUE TITLE
check box and radio button images are incomplete

### ISSUE THREAD

**Issue by adrianknight89** [google/material-design-icons#461]
Please see: https://github.com/google/material-design-icons/tree/master/toggle/ios

Can we have more check box and radio button icons (different resolutions) so that they are on par with others?

**Comment by jestelle** [comment]
Can you clarify what you're asking for?
I believe it may be the fact that most icons we provide 18dp, 24dp, 36dp, and 48dp
Where for checkbox and radio buttons we only provide 24dp.

This is because we encourage folks to keep checkbox and radio controls a consistent size.

Please reopen with more detail.
