### ISSUE TITLE
Icon Request: Social Sites Icons 

### ISSUE THREAD

**Issue by tenshiAMD** [google/material-design-icons#480]
Could you guys make icons for social site like Facebook, Instagram, Tumblr, Twitter, LinkedIn and etc. ? I'm using angular-material as the design framework. It would be useful and easy to use if there are icons and icon-fonts like those. Thank you.

**Comment by TheChrisPratt** [comment]
I don't believe they can. Those are trademarked symbols.

On Sep 14, 2016 10:08 PM, "Angel Aviel Domaoan" <notifications@github.com>
wrote:

Could you guys make icons for social site like Facebook, Instagram, Tumblr,
Twitter, LinkedIn and etc. ? I'm using angular-material as the design
framework. It would be useful and easy to use if there are icons and
icon-fonts like those. Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/material-design-icons/issues/480>, or mute the
thread

**Comment by controversial** [comment]
@TheChrisPratt But ionicons and Font Awesome include social icons.

**Comment by TheChrisPratt** [comment]
Not my decision, just what's been said here whenever they've been asked for.
  (*Chris*)
