### ISSUE TITLE
Icon Request: icons for numerals

### ISSUE THREAD

**Issue by goodnesskay** [google/material-design-icons#533]
There should be icons for numerals like(1,2,3,4) that we can employ in our projects. It does not have to be more than number 10 just for some listing at the front-end

**Comment by biggoron** [comment]
Hi goodnesskay,
I was scrolling over the issues in hope of finding a simple task to work on, to practice my infographics while contributing to open source. Your problem seems simple enough for me to get a try on it but can you please precise what you wish icons for numerals would bring that a text font wouldn't?

**Comment by RoelN** [comment]
Closing this because it's an ancient issue. Apologies for leaving it open for so long. If you feel it's still relevant, feel free to reopen or create a new one with updated information!
