### ISSUE TITLE
Remove useless path

### ISSUE THREAD

**Issue by nt1m** [google/material-design-icons#61]
There's a path with fill: none;, when I remove it, it has no effect on the icon. That path can be removed, unless it's a signature from Google ?

**Comment by jestelle** [comment]
You can remove it, or just use the svgs in the 'production' folders, which already have it removed.
The reason it's there is to assist designers when they drop SVGs into mocks.  That path helps tools like Illustrator and Sketch align the icon correctly to the intended edge rather than the optical edge of the icon, if that makes sense.
