### ISSUE TITLE
Inconsistent numbering on looks icons

### ISSUE THREAD

**Issue by aciccarello** [google/material-design-icons#680]
The number on the looks icons switches from numerals to words between "two" and "3". Could this be made more consistent? The filter icons use only numbers.

![image](https://user-images.githubusercontent.com/11273838/30559658-99b789c8-9c72-11e7-9b29-84c41f043bd2.png)

**Comment by tphinney** [comment]
I suspect I know how this happened, although it does not fix it.

When the looks icons were being made, originally there were only two numbered ones. The numbers “one” and “two” happen to be in the same order whether expressed with letters or numerals. That is not true for the larger numbers, so they switched to numerals instead of letters.

BUT there were backwards compatibility concerns, so they kept what they had for one and two.  :/

With filters either they were made all at once, or they learned from previous mistakes.
