### ISSUE TITLE
Icon Request: Percent

### ISSUE THREAD

**Issue by JSMike** [google/material-design-icons#699]
There's currently no `%` symbol for material icons font.

**Comment by Gaboik** [comment]
I would like to have that icon too!

**Comment by marcoiai** [comment]
I need it too!

**Comment by hasleraj** [comment]
I need this too!

**Comment by ryanblaq** [comment]
I also need this!

**Comment by abhijeetahuja** [comment]
+1

**Comment by ebellumat** [comment]
I need this too!

**Comment by IvanovPvl** [comment]
I also need this.

**Comment by fengxiaoyue** [comment]
I also need this!

**Comment by kevzlou7979** [comment]
I need this +1

**Comment by darvishzadeh** [comment]
there are 8 airline seat positions, but no percentage symbol? outrageous!

**Comment by Montesdodgers13** [comment]
Closed

**Comment by nicholasp** [comment]
+1 PLEASE!

**Comment by IhorHolovatsky** [comment]
I found that this is working:
`<mat-icon [inline]="true" matPrefix>$</mat-icon>`

**Comment by cleitonoliveira** [comment]
Just put the "%" symbol and surprisingly it works. Didn't like its style that much but used it anyway.

**Comment by sainture** [comment]
+1

**Comment by mdublin** [comment]
This got me pretty close:
`<i [inline]="true"><b>%</b></`i> or `<i [inline]="true" class="material-icons"><b>%</b></i>`

**Comment by NodeSwapCeo** [comment]
And another one missing for years, sure this design is supported by google ...

**Comment by omidh28** [comment]
+1

**Comment by idaWHALE** [comment]
please...

**Comment by ebellumat** [comment]
Google Abandoned this icons like the same way they will abandon the Android for launch Fuchsia

**Comment by cyberalien** [comment]
Yes, it does seem abandoned.

Good news is license is open source, so anyone can clone and update it. That's what I did: https://github.com/cyberalien/google-material-design-icons-updated

That repository includes latest icons from material.io in 5 variations (baseline, outline, round, sharp, twotone) for each icon. I fixed bugged icons and re-added all icons that were removed since version 3. Also there are few custom icons.

I've added percentage icon:
![baseline-percentage.png](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/math/baseline-percentage.png) [baseline-percentage.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/math/baseline-percentage.svg)
![round-percentage.png](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/math/round-percentage.png) [round-percentage.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/math/round-percentage.svg)

For outline and twotone versions I've slightly increased circles, otherwise they'd be identical to baseline:
![outline-percentage.png](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/math/outline-percentage.png) [outline-percentage.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/math/outline-percentage.svg)
![twotone-percentage.png](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/math/twotone-percentage.png) [twotone-percentage.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/math/twotone-percentage.svg)

Its not available as font. Instead icons are available with [Iconify SVG framework](https://iconify.design/) that behaves similar to font and as React component.

Enjoy :)

**Comment by gagan95** [comment]
+1

**Comment by ebellumat** [comment]
I Giving up this lib, i'm moving to 
https://materialdesignicons.com/

**Comment by alexandrebuisson** [comment]
Up

**Comment by morfinismo** [comment]
I was in the same position... I dont know about you guys but for me it worked by literally using the "%" sybmol.

`<i class="material-icons">%</i>`

**Comment by korbi-oranssi** [comment]
+1

**Comment by DanishWasim** [comment]
Friends try this for percentage  &#37;

**Comment by Chargnn** [comment]
+1

**Comment by nirakar5656jad** [comment]
+1

**Comment by rednikisfun** [comment]
+++

**Comment by shubhamappstec** [comment]
+1

**Comment by wucdbm** [comment]
++

**Comment by btechn01** [comment]
+1

**Comment by woteska** [comment]
+1

**Comment by Soullighter** [comment]
+++

**Comment by sreerajsomarajan** [comment]
+1

**Comment by JayPatel52970** [comment]
+1

**Comment by CodeWithKamal** [comment]
+1

**Comment by sushilvangar** [comment]
+1

**Comment by gasbasd** [comment]
please

**Comment by benounnas** [comment]
+1

**Comment by franalt** [comment]
+1

**Comment by jalpadoshi** [comment]
Icon now available on:  https://fonts.google.com/icons

**Comment by amiyoghoshstar** [comment]
still not available

**Comment by TylerJenningsW** [comment]
still not available!

**Comment by tphinney** [comment]
Still available. See the link given above.
