### ISSUE TITLE
How to find &#x... charset??

### ISSUE THREAD

**Issue by RicardPG-Vintra** [google/material-design-icons#774]
Hi,

I don't find the charset associated to a icon.. before the updates I extract it from material-icons website.. now i don't know how to find it.

Please can someone help me?

Thanks!

**Comment by vinnykov** [comment]
It looks like a bug on the website that the codes are missing, because I don't see any difference in the proposed usage code for old and new browsers. The snippet for old browsers should include the code.

If by some reason codes were removed, it makes sense to update this file for those of us, who need to use the codes: https://github.com/google/material-design-icons/blob/master/iconfont/codepoints. This file was updated 2 years ago and don't include the new changes.

The proposed usage code on the website (no difference between the "For modern browsers" and "For IE9 or below").

<i class="material-icons">
cancel
</i>

<i class="material-icons">
cancel
</i>

**Comment by RicardPG-Vintra** [comment]
In my opinion is a bug... Hope that can fix it, but meanwhile maybe will be usefull the codepins. 

Thanks for the info!

**Comment by marceloromaomultilaser** [comment]
Please, fix this!!

**Comment by shabib3** [comment]
I created this for who ever needs - https://github.com/google/material-design-icons/issues/813#issuecomment-401601344

**Comment by RoelN** [comment]
The codepoints can now also be found in the `.codepoints` files here: https://github.com/google/material-design-icons/tree/master/font
