### ISSUE TITLE
toggle_off and toggle_on icons is missing

### ISSUE THREAD

**Issue by VitushaVitaly** [google/material-design-icons#780]
Hello,
There are missing icons like toggle_off and toggle_on
https://material.io/tools/icons/?icon=toggle_off&style=baseline
https://material.io/tools/icons/?icon=toggle_on&style=baseline

Does anyone have any idea why?

**Comment by shengslogar** [comment]
I just encountered the same issue.

**Comment by Magnusri** [comment]
Same problem here,

**Comment by striky1** [comment]
Same problem

**Comment by moizang** [comment]
I had the same issue today and found this :
https://github.com/google/material-design-icons/issues/655

It seems that they do not plan on adding them 😞

**Comment by thiswallz** [comment]
same here guys, some one found something? thanks

**Comment by thw0rted** [comment]
@shyndman could you clarify your statement from #655 now that toggle icons (linked in the OP here) have in fact been added? I'm hoping that you *meant* "we don't plan on adding a toggle icon", but the team later changed their minds, rather than "there's a toggle icon but it won't be added to the font", which wouldn't really make sense.

@VitushaVitaly , if that's the case, your question is really "why aren't the new icons from [the online index](https://material.io/tools/icons/) being added to this repository" which is the same as #786 -- you might want to follow that issue.

**Comment by alecogt** [comment]
I have the same issue. The icons are shown in the docs (https://material.io/tools/icons/?icon=toggle_on&style=baseline), so I guess they should be either included with the font or removed from the docs.

**Comment by thw0rted** [comment]
@alecogt if you read #786 you'll see that you can use the font with icons in it right now, just not via the (woefully outdated) NPM package.

**Comment by alecogt** [comment]
Thank you @thw0rted. The toggle_on and toggle_off icons are not included even when included from https://fonts.googleapis.com/icon?family=Material+Icons

**Comment by thw0rted** [comment]
Yikes! I hadn't tried it and just assumed that the index site (on material.io) used the font -- on inspection, it looks like they have individual files per icon instead.  So, yeah, the whole project is in a weirdly stalled state, considering how active the rest of Material has been lately.

**Comment by finex** [comment]
Same problem here.

**Comment by FlawaCLV** [comment]
`nights_stay` is on the website but missing in the 3.0.1 exports...

**Comment by thw0rted** [comment]
This project is basically abandoned, it seems like everybody is switching to [the iconfont repo](https://github.com/jossef/material-design-icons-iconfont) instead.

**Comment by finex** [comment]
Ok, thank you @thw0rted :-)

**Comment by RoelN** [comment]
The icons seem to have been added in the meantime:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/4570664/107341237-029be100-6abf-11eb-94b1-6d3f5d74ce72.png">

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
