### ISSUE TITLE
Icons missing in https://material.io/icons/

### ISSUE THREAD

**Issue by ackushiw** [google/material-design-icons#789]
So I can use `content_copy` `content_cut` `content_paste` but the documentation for them is missing on the material.io website.

**Comment by TheMacNerd** [comment]
Here is a possible solution to your problem:

https://www.technipages.com/android-icons-disappear-from-home-screen

**Comment by thw0rted** [comment]
I don't think this is the right tracker for documentation issues.  The icons you named are present in the latest NPM package but they're not listed on the website.  I'm not sure if that's because the package is so old, and the icons are actually removed, or if the docs are just wrong.  If it's the latter, there's a "feedback" link at the bottom of the material.io website that would let you report it.  If it's the former, see issue #786 for instructions on getting the newer files.

**Comment by mehdi-yeganeh** [comment]
We have icon for pregnant woman in the Action category!! but we have not any icon for Cut, Copy & Paste. Why you removed these icons? **We need them!**

**Comment by thdk** [comment]
content_paste, content_copy and copy_cut currently still work in material design components web.

**Comment by george-hawkins** [comment]
As noted by @thdk, clipboard related icons **are** available. However, they're not included on the main [Material icons reference page](https://material.io/resources/icons/). This _seems_ like a bug to me.

They've been around since the third commit, way back in 2014: [`95c4d7a:/index.html:302`](https://github.com/google/material-design-icons/blame/95c4d7a/index.html#L302). So it's not like they're a recent addition.

You can see them all listed in [`/sprites/svg-sprite/svg-sprite-content.html`](https://github.com/google/material-design-icons/blob/master/sprites/svg-sprite/svg-sprite-content.html) (which is you can view properly rendered using raw.githack [here](https://raw.githack.com/google/material-design-icons/master/sprites/svg-sprite/svg-sprite-content.html)).

To use them in Angular you just have to drop the leading `ic_`, so e.g. `ic_content_copy` becomes `content_copy`:

```
<mat-icon>content_copy</mat-icon>
```

**Comment by RoelN** [comment]
Thanks for reporting, the icons have been added in the meantime!
