### ISSUE TITLE
Refresh to material icons font site causing compatibility issues

### ISSUE THREAD

**Issue by burnleydev** [google/material-design-icons#793]
We have previously built sites using material icon fonts, and used **numeric character references** to ensure compatibility with older browsers:

**Old browser - numeric character references**
`<i class="material-icons">&#xE853;</i>`

**New browser - ligatures**
`<i class="material-icons">menu</i>`

Nowadays we use **ligatures** in the main but the **numeric character references** are still useful as this approach allows them to be used in styles without additional html markup. For instance, a 'external site' icon at the end of a link. We do this by putting the **numeric character reference** in the content of a pseudo element.

```
.material-icon::before {
    content: "\E835";
}
```

Now when requesting an icon font through the material icon site, the ligature signature  is the default for both modern browsers and older browsers. I'm guessing this is an error rather than it being the case that IE9 has been made to work with ligatures.

The point is that I no longer have access to the **numeric character references** - where can I find them?

**Comment by TangSteven** [comment]
Duplicate, please view #774

**Comment by RoelN** [comment]
The code points (numeric character references) are now here: https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints and they will still work, alongside the ligatures.

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
