### ISSUE TITLE
Icons are missing

### ISSUE THREAD

**Issue by megabast23** [google/material-design-icons#798]
Hello,
some icons are missing regarding  https://material.io/tools/icons/ website.
It would be awsome to get last icons in your github.

Best regards,
Bastien

**Comment by niutech** [comment]
The version in https://github.com/google/material-design-icons/tree/master/iconfont is 2.2.0, whereas Google Fonts has the latest version of them:
https://fonts.googleapis.com/icon?family=Material+Icons
https://anonfile.com/31EcH8e2b9/Material_Icons.woff2
https://anonfile.com/6dE7H7efbf/Material_Icons.woff

(Please correct `ares` to `are` in the title)

**Comment by pollito05** [comment]
Hahahaha megafraca

**Comment by megabast23** [comment]
@pollito05 very interesting comment...

**Comment by BOLL7708** [comment]
Even if I use Google's embed linked in @niutech 's reply I still miss the icons I want to use, I have a JSFiddle of it [here](https://jsfiddle.net/BOLL/bdhuc4m1/2/), this is following the instructions on the Material.io site which also links here for self-hosting but those files (as this issue is about) also lack the icons... ?

**Comment by visualbyte** [comment]
If I download the icon file, the version still says 1.011 in the properties. And, it is not as per the latest Google Material Icons website.

Please update here as well

**Comment by nyankobu010** [comment]
I've added the links to download the latest font files in issue #786 at the bottom, @BOLL7708 trying the updated links, they should contain all the recent icons.

**Comment by maurusrv** [comment]
hi, i've explored the material-designs-icons-iconfont, but what i needed is the SVG files. is there any other library to import image rather than type? many thanks!

**Comment by baartho** [comment]
It has been over one year since this issue was opened. 

It would be great if all icons were on the official website.

**Comment by Kazem-ma79** [comment]
I was using the CDN and all icons were correctly showing but when I installed package via npm some icons are missing (eg. minimize - maximize - aspect_ratio).

**Comment by moshequ** [comment]
> Hey @megabast23 @niutech @pollito05 @megabast23 @visualbyte
> 
> This project is on low maintenance and out of date for a while.
> 
> The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.
> 
> ### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)
> ![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**To import from style.scss use:**
```$material-design-icons-font-directory-path: '~material-design-icons-iconfont/dist/fonts/';```

```@import '~material-design-icons-iconfont/src/material-design-icons';```

**Comment by Julian-B90** [comment]
emoji_objects are missing.

**Comment by PassionPenguin** [comment]
oh thx for that
i've tried a lot to find but failed....
now i found it
thx for the issue

**Comment by modbender** [comment]
Why is there no google icon in material icons?

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.

The assets have been updated since this issue was reported, some of the specifics in the issues have been fixed by that. If not, feel free to reopen this issue or create a new one with more information.
