### ISSUE TITLE
latest stable link icons zip isn't up to date

### ISSUE THREAD

**Issue by shabib3** [google/material-design-icons#814]
Hi,

I am following the [Material Icons Guide](https://google.github.io/material-design-icons/#icon-images-for-the-web) for developer, and I reached the part of `Downloading everything`, and there you give me link to the [latest stable zip archive](https://github.com/google/material-design-icons/releases/download/3.0.1/material-design-icons-3.0.1.zip).

But I found out that this is not the up to date...there is a lot of missing icons like `delete_outline(e92e codepoint)` or `calendar_today(e935 codepoint)`

Notice that I mentioned the codepoints because I use it in my project.

Those are really awesome icons, pls update the zip.

Thanks a lot :)

**Comment by vegansk** [comment]
npm package needs to be updated too!

**Comment by poiru** [comment]
To obtain a URL to the latest TTF, you can use:

```
curl https://fonts.googleapis.com/icon?family=Material+Icons
```

As of this post, the returned URL points to https://fonts.gstatic.com/s/materialicons/v38/flUhRq6tzZclQEJ-Vdg-IuiaDsNZ.ttf (font revision 1.017, created on May 18, 2018)

**Comment by poiru** [comment]
See #786

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported. The codepoints have been updated. Please see this new zip here: https://github.com/google/material-design-icons/releases/tag/4.0.0

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information!
