### ISSUE TITLE
commute icon not available for use in version 3.0.1

### ISSUE THREAD

**Issue by mattLarson** [google/material-design-icons#819]
commute icon not available to use in version 3.0.1, like:

``
<i class="material-icons">commute</i>
``

**Comment by eelcowen** [comment]
Please read #786 
Google isn't updating this repo for the foreseeable future.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

Also, this looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
