### ISSUE TITLE
Can material icons be used in products that i sell ?

### ISSUE THREAD

**Issue by user-mk** [google/material-design-icons#822]
Hello,

can i use material design icons in products i sell. the icons will be included together with my product when i sell my product.

so can material design icons be used in products that i sell ?

MMK.

**Comment by Aspie96** [comment]
The confusion makes sense.
The product is released under Apache license, but Google asks not to sell it. This requirement is incompatible. See #424 and #605.

This creates a lot of confusion about the license, in my opinion.

**Comment by ConfusedVorlon** [comment]
It seems pretty clear to me. The licence governs the legal terms.

Additionally, they _ask_ that you don't resell the icons themselves (e.g. don't sell material icon pack containing just the icons)

You can legally ignore their request (I'm assuming that the Apache the licence gives you permission to sell the icons) - but it would reflect poorly on your moral character.

**Comment by Aspie96** [comment]
Not clear at all.
To write it in the "license" section is misleading, considering how many
people already don't understand such licenses.

Of course one can ask whatever they wish, but then it must be a bit clearer.

> I'm assuming that the Apache the licence gives you permission to sell the
icons
It does, since it is a free software license. Every free software license
does.
The Apache license allows you to distribute copies of the work and doesn't
prevent distribution for a fee. If you add any clause, it's no longer the
Apache license.

> but it would reflect poorly on your moral character.
I don't intend, myself, to distribute the icons, whether for free or not,
but I disagree with this statement.
If you apply a license to one of your works, you are giving a permission.
If you don't want people to do something with your work, just apply a more
restrictive license.

Regardless, a better wording could be:
> We have made these icons available for you under the Apache License
Version 2.0 to incorporate into your products [The previous wording might
suggest the product itself need to be under Apache, which isn't true]. Feel
free to remix and re-share these icons and documentation in your products.
We'd love attribution in your app's about screen, but it's not required.
We'd prefer you not to re-sell these icons.

Saying "ask" in a section call "license" can be interpreted by some as a
legal requirement. And you can see that in some other issues: people
(including myself) do find it confusing.
If it is something that is kindly asked, rather than a requirement, then it
shall not look like a (legal?) requirement.

Please see: https://www.gnu.org/philosophy/selling.html. Note that Apache
2.0 is a free license and, also, that the page does not only apply to
selling your own software.

Il giorno lun 23 dic 2019 alle ore 15:18 ConfusedVorlon <
notifications@github.com> ha scritto:

**Comment by RoelN** [comment]
🥳 https://github.com/google/material-design-icons/pull/605
