### ISSUE TITLE
Adding dev.to

### ISSUE THREAD

**Issue by Berkmann18** [google/material-design-icons#837]
[dev.to](http://dev.to/) is an ever growing community of developers and I was wondering if it was possible to get their svg as part of the icon set so it could be used the same way as other material design icons?

Here's the aforementioned SVG:
![dev.to](https://camo.githubusercontent.com/6bc5e62e0bf5e21ab8054b731540529bbc8e01b3/68747470733a2f2f6432666c746978307632653073622e636c6f756466726f6e742e6e65742f6465762d62616467652e737667)

**Comment by miku86** [comment]
Any news on this one?

With nearly 12M visitors/month this is one of the biggest networks and blogging platforms for developers.

I think a lot of developers who use MaterialUI would love to have a "native" integration, because this is much easier than integrating the existing [Font Awesome Icon](https://github.com/FortAwesome/Font-Awesome/issues/12589), therefore an official Material Design Icon would be awesome.

I think @benhalpern would also be happy if this happened.

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
