### ISSUE TITLE
No helpful list of the entire icon library's names/codes

### ISSUE THREAD

**Issue by ncmancuso** [google/material-design-icons#858]
I am trying to build a component that lists the Material icons so that a user could select one to use. The component accepts a list that it can loop through and build the component, but this list isn't available anywhere in the package (not that I could find).

I found the codepoints file found [here](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints). This isn't in a usable structure.

Expected:

I'd like a JSON file with all the icon names/code that can be used as a parameter for such components. This file should include categories similar to how the icons are organized on your website. 

Actual:

I had to manually create a file like this in order to create my component which will become a maintainability nightmare.

**Comment by RoelN** [comment]
The codepoints files [here](https://github.com/google/material-design-icons/tree/master/font) are in `name codepoint` format. There are no plans to include a JSON file but you could create one based on the codepoints for your project.

**Comment by jsejcksn** [comment]
> I had to manually create a file like this…

For anyone else who discovers this issue:

Here's a function `parseCodePoints` that will parse the text from one of the `*.codepoints` files into an object mapping of `id -> codePoint`. You can use the function locally with the files in the repo via Node.js/Deno/etc. or just copy + paste the entire script into your browser's JS console, and it should print the list for you there.

In Chrome DevTools, you can [store the object as a global variable](https://developer.chrome.com/blog/new-in-devtools-71#store) and then use the [`copy()`](https://developer.chrome.com/docs/devtools/console/utilities#copy-function) function to copy a JSON serialization of it to your clipboard. Otherwise, you can manually modify the script to use [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).

[Code in TypeScript Playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&removeComments=true&target=99&jsx=4&exactOptionalPropertyTypes=true&inlineSourceMap=true&inlineSources=true&isolatedModules=true&noImplicitOverride=true&noErrorTruncation=true#code/BQQwzgngdgxgBMAlHAvAPjgbwFBzgMwFdYAXASwHso4AHEAJzAFMBhCgEyYAUKyoSwwGB269+YADJkwJAFxwZ9PgHNE8gEpNh9dgB5FKgDQKSSqMow48eYVBlx6TMIQA2cuJu16D54z4uoWAC+ANy41vgU9Ai29i58THAU+HDCnDx8AlIyAHSmZAC2SDlgNPEkwAD0ADr0APzVUJWIyFbWNlT2fJwAHoHxUEw53Uw9APL4wABEcFOIYe14ZCnAAITAI30YAAxwAGR7cANDLkzmJAAWcBibcADUcACMLVjhi3CX9BQA7nCDvwBRehfejAAAGAFVBj0aFoSEx2EcEnAAG4gFyEJiyRoAEkwxyCYPmb2sQRJeEczjcAG1jiV4jAmMBtsZNogALr9BL0siMjZQXr3J7E9pk9qOEiEejUSmuEgLOBk8LgaDwIikSjUfBMEgwC5sdJiATAEnKMgkAAShAARuoQN8IfQXAAxKIG0SZMDOsineT+QzhNRwLhfArSJi6TxRbz5XwmMwWSwk2IkBxOGidRIoOD2kDmgg6vXAM2Wm12h1O130d0ZcTe04i6zLBCrSkZuxDCgAa2Qnx+fyYgOBUWmmlKmb+FFTYwA0nMFRSdVLqHRGKwRLXjbn823M3lRhUWgqlR07Km0h7xIFt6ntbr9RujYISZVKnAhsocnACiB4Up0QoEAFNaFAuGASSECQxzsLIJJTBcJAkDQYCyK+9D2jkJYXDahDMPQtjwvwOTCAUlTKBQFDKKclQ-n+ZDogAtJwYBkMoUAMbynQ0eAf6VGi-7WqckT8JUACyv5MP+LgAMpASBYFjJB0EAKQAKwAELOgAkhIEjKQATCwADi6gAIIACIGWwyEAF5Wd8ygIWp5nESIGaelMAZ4MS4SxKBJyUcAbQdIanpedYr5wGM0RUC4EAfBciRaeZKEkmQ7AoVF1oAFZwjkXZMBAggXpuYCIOFQTEpVSBhEAA)

```js
(async () => {
  function parseCodePoints(codePointsList) {
    const result = {};
    for (const line of codePointsList.trim().split(/\r?\n/)) {
      const index = line.indexOf(" ");
      if (!(index > 0 && line.length > index + 1)) {
        throw new Error(`Unexpected line value:\n${line}`);
      }
      result[line.slice(0, index)] = line.slice(index + 1);
    }
    return result;
  }

  async function fetchCodePoints(gitHubRawUrlForCodePointsFile) {
    const response = await fetch(gitHubRawUrlForCodePointsFile);
    if (!response.ok) throw new Error("Response not OK");
    return parseCodePoints(await response.text());
  }

  const codePoints = await fetchCodePoints(
    // e.g. material symbols outlined:
    "https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints",
  );

  console.log({
    codePoints,
    // Or only the IDs:
    ids: Object.keys(codePoints),
  });
})();
```
