### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [google/material-design-icons#901]
What is the current status of the project?
The last commit was ~1 year ago and there are changes since the last release: https://github.com/google/material-design-icons/compare/3.0.1...master

**Comment by MicMicMon** [comment]
@jestelle any idea by chance?

**Comment by cyberalien** [comment]
Seems abandoned.

Good thing its open source, so I've made a repository with latest icons: https://github.com/cyberalien/google-material-design-icons-updated

It contains latest icons from material.io, I've fixed few icons that were bugged or had wrong size.

Currently repository has only icons in SVG format 24x24. All icons have been optimised and cleaned up.

Instead of font its available with Iconify JavaScript SVG framework that is as easy to use as glyph font, but renders SVG.

React components are available too.

If you need any other format (except for font because new icons aren't really usable for font), please open issue and I'll try to add that format to repository.
