### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by jleppert** [google/material-design-icons#951]
The last commit is way back in January. Has Google abandoned this project as they frequently do?

**Comment by jossef** [comment]
This project is on low maintenance and out of date for a while.

I've forked this repo, scraped the updated fonts from `Google Fonts` CDN, added support for scss, removed irrelevant files (jams `npm install`).
+ has offline support

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/49375637-98809800-f70d-11e8-9491-29d2cfd05b17.png)

**Comment by inorganik** [comment]
Thanks @jossef.

@acdvorak - should https://material.io/resources/icons/ be linking here when this repo hasn't been committed to in almost 2 years? I spent a fair amount of time troubleshooting why a particular icon wouldn't work only to find this is way out of sync with what's displayed on that page.

**Comment by cary-smith** [comment]
So I have a process that screen-scrapes the website for the svgs. We just recently updated it and it looks like certain icons are now missing/removed like "edit_location". 

@jestelle - Is there a consistent source to retrieve the SVG icons from since this one does not match and the output on the web site and the icons from said site are now changing (someone is working on it)?

**Comment by jestelle** [comment]
Hi Capt,
Unfortunately I'm no longer working on Material Design and I don't have
much info to offer. I'll reach out to the folks currently responsible for
Material Design icons and see if I can get some of their attention here.
Sorry I can't be of more help!
Best,
Josh

**Comment by cyberalien** [comment]
@jestelle there are couple of community projects that continue maintaining material icons.

They are all smaller repositories. One common issue with this repository is its huge because it contains many different formats. So all community repositories contain only 1 icon format:

@jossef has icon font split into separate repository: https://github.com/jossef/material-design-icons-iconfont
Its same font as in this repository, but updated version. It contains only font.

I maintained SVG repository for some time: https://github.com/cyberalien/google-material-design-icons-updated
It contains official icons in "original" branch, "master" branch also includes some custom icons. Also fixed some icons that were broken and re-added icons that existed in version 3 that is in this repository, but were removed in version 4 that is currently on material.io. Then there are some custom icons that were requested in this repository.

Recently we've been discussing joining forces to maintain updated icons. This is what came out of it: https://github.com/material-icons
Its new, still work in progress. It includes SVG, generated PNG and font. Font is different though - it doesn't use ligatures because they fail with two tone icons in older browsers. Also with my Iconify project icons are available as SVG framework that replaces icon font with more modern solution and React component.

If you get in touch with people who are maintaining material icons now, please mention those repositories. Maybe we can join forces or they can officially endorse those projects (and repositories can be changed to match their requirements).

**Comment by danger89** [comment]
Lets join forces!

**Comment by cary-smith** [comment]
I like the idea of joining forces, but there is work _currently_ being done to the MD Icons website that includes updates. I have been screen-scraping the SVGs every so often (brittle, but at least it was up to date) and the script failed do to the changes they are making. 

If the community builds its own and Google maintains its own, then its still a split concept requiring items to be 'synced' whenever they decide to update (like they are doing now). Someone is updating the icon site but chooses not to provide insight beyond the downloads which is a bit of a bummer. Personally I would prefer a single source of information and if possible, a SVG-only version of the library.

**Comment by rsheeter** [comment]
FYI, we are working on bringing this repo back to life. #1054 has additional context.
