### ISSUE TITLE
material-design-icons make my my grunt watch task freeze

### ISSUE THREAD

**Issue by casertap** [google/material-design-icons#96]
the grunt serve command freeze
````
Running "concurrent:ionic" (concurrent) task
Running "ionic:serve" (ionic) task
Running "watch" task
Waiting...
````

I'm on mac osx.
I saw articles saying:
On most systems the maximum number of watches that can be created per user is limited to 8192. watchdog needs one per directory to monitor. To change this limit, edit /etc/sysctl.conf and add:
fs.inotify.max_user_watches=16384

but it does not help.
I have a basic setting (I keep the bower_components folder outside of app but I copy it inside of www during the dist task:
/app
------/images
------/styles
------/index.html
/bower_components
....
/www
-------/bower_components
-------/images
-------/styles
-------/index.html

my watch part look like this
````
watch: {
      bower: {
        files: ['bower.json'],
        tasks: ['wiredep', 'newer:copy:app']
      },
      html: {
        files: ['<%= yeoman.app %>/**/*.html'],
        tasks: ['newer:copy:app']
      },
      js: {
        files: ['<%= yeoman.app %>/<%= yeoman.scripts %>/**/*.js'],
        tasks: ['newer:copy:app', 'newer:jshint:all']
      },
      compass: {
        files: ['<%= yeoman.app %>/<%= yeoman.styles %>/**/*.{scss,sass}'],
        tasks: ['compass:server', 'autoprefixer', 'newer:copy:tmp']
      },
      gruntfile: {
        files: ['Gruntfile.js'],
        tasks: ['ngconstant:development', 'newer:copy:app']
      }
    },
````

**Comment by robertbaker** [comment]
The issue is with your tasks, not this project. I wouldn't copy bower_components anywhere. You should use Wiredep for injecting bower components. On a serve task, it will reference the files straight from bower_components. On a dist task, it should concat those files into a file like vendor.js.

You can find better Yo generators. Personally, I would pick https://github.com/Swiip/generator-gulp-angular. It uses gulp which is a lot better than grunt and works fine with material-design-icons.

Personally I use a gulp-sprite plugin that takes the icons that I need and builds a custom sprite.

**Comment by jestelle** [comment]
Robert's suggestion looks good.  Please reopen if you still have questions here.
