### ISSUE TITLE
Settings icon missing on web

### ISSUE THREAD

**Issue by washeck** [google/material-design-icons#966]
Icon "settings" is not found when searching on https://material.io/resources/icons/?style=baseline

**Comment by maxloh** [comment]
I think they deleted it intentionally

**Comment by Fredericco72** [comment]
Check this thread out #502, even though it's not advertised, 'settings' still works...

`<i class="material-icons">settings</i>`

**Comment by RoelN** [comment]
![image](https://user-images.githubusercontent.com/4570664/105726960-e0388e00-5f2a-11eb-8ad0-1767dcfb1e13.png)

The icon is there, and can be found here https://github.com/google/material-design-icons/tree/master/src/action/settings

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
