### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by alijmlzd** [google/material-design-icons#977]
I think there are no longer updates on this project since 2018.
Another reason is that some of the icons are not included in the font-icon and will display empty space instead.
Such as ballot, speed, contactless, text_rotation_angle_*, missed_video_call, policy and ...
You can try and see most of the new material icons displaying in the docs website are not included in this repository via font-icons and you can not use any of them.
So can we say this project is dead and will not be updated anymore and it is better to choose alternatives?

**Comment by progmars** [comment]
I wanted to get offline fonts for my customer's intranet app, so I installed this one.... and many icons disappeared.

Google's own CSS leads to a file
https://fonts.gstatic.com/s/materialicons/v50/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2

which is clearly not the same MaterialIcons-Regular.woff2 as included in this repository because there's 20KB difference.

**Comment by StLa1** [comment]
I think so

**Comment by RoelN** [comment]
The font in the repo has been updated, and fonts.gstatic.com always has the most up-to-date one as well. So I'm closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
